# Myth Dark Pointed config for Starship
# (c) 2020 by Mick Hohmann, last changed 2020-10-22 23:08

# Don't print a new line at the start of the prompt
add_newline = false

# Order of modules on prompt
format = """\
$username\
$hostname\
$directory\
$aws\
$gcloud\
$singularity\
$kubernetes\
$docker_context\
(‚Üì Source control - for right side ‚Üì)\
$hg_branch\
$git_branch\
$git_commit\
$git_status\
$git_state\
(‚Üë Source control - for right side ‚Üë)\
(‚Üì Toolchain version modules ‚Üì)\
$crystal\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$java\
$julia\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$swift\
$terraform\
$zig\
(‚Üë Toolchain version modules ‚Üë)\
(‚Üì Package modules ‚Üì)\
$helm\
$package\
$cmake\
$conda\
(‚Üë Package modules ‚Üë)\
$nix_shell\
$memory_usage\
$env_var\
$custom\
(‚Üë above input line ‚Üë)\
$line_break\
(‚Üì on input line ‚Üì)\
$battery\
$shlvl\
$jobs\
$status\
[‚ï∞‚îÄ](bold cyan)$character"""
# $character"""

# Generic prompt configurations
[character]
success_symbol = "[ÔÅî](bold cyan)"
error_symbol = "[ÔÅî](bold cyan)"

[line_break]
disabled = false

# Module configurations
[aws]
# disabled = true
symbol = " ÓåΩ "
style = "bg:#EC912D"
format = '[[ÓÇ≤](bg:#000000 fg:#EC912D)$symbol$profile(\($region\))[ÓÇ∞](bg:#000000 fg:#EC912D)]($style)'

[cmake]
# disabled = true
symbol = " Ô®∂"
style = "bg:#064F8D fg:#EEEEEE"
format = "[[ÓÇ≤](bg:#000000 fg:#064F8D)$symbol$version[ÓÇ∞](bg:#000000 fg:#064F8D)]($style)"

[conda]
# disabled = true
symbol = " ÔÑå "
style = "bg:#43B02A fg:#111111"
ignore_base = true
truncation_length = 1
format = "[[ÓÇ≤](bg:#000000 fg:#43B02A)$symbol$environment[ÓÇ∞](bg:#000000 fg:#43B02A)]($style)"

[crystal]
# disabled = true
symbol = " Ôàô "
style = "bg:#EEEEEE fg:#111111"
format = "[[ÓÇ≤](bg:#000000 fg:#EEEEEE)$symbol$version[ÓÇ∞](bg:#000000 fg:#EEEEEE)]($style)"

[dart]
# disabled = true
symbol = " Óûò " # original
style = "bg:#32BBF9 fg:#111111"
format = "[[ÓÇ≤](bg:#000000 fg:#32BBF9)$symbol$version[ÓÇ∞](bg:#000000 fg:#32BBF9)]($style)"

[directory]
style = "italic bg:#6F6A70 fg:#EEEEEE"
read_only = "Ô†Ω"
read_only_style = "bg:#ff3322 fg:#EEEEEE"
truncation_length = 8
truncate_to_repo = true
# truncation_symbol = " ‚Ä¶"
# fish_style_pwd_dir_length = 3
format = "([[ÓÇ∞](bg:#ff3322 fg:#000000)$read_only[ÓÇ∞](bg:#000000 fg:#ff3322)]($read_only_style))[[ÓÇ∞](bg:#6F6A70 fg:#000000) $path [ÓÇ∞](bg:#000000 fg:#6F6A70)]($style)[[ÓÇ∞](bg:#AFD700 fg:#000000)ÓÇ∞](fg:#AFD700)"

[directory.substitutions]
"~/Documents" = "Ôúô"
"~/Music" = "Ô¢É"
"~/Movies" = "Ôóº"
"~/Pictures" = "Ôõû"
"~/Sources" = "ÔÑ°"
# "~" = "Ôë≠ "
"/" = " ÓÇ± "

[docker_context]
# disabled = true
symbol = " Ôåà "
style = "bg:#3A91DC  fg:#EEEEEE"
only_with_files = true
format = "[[ÓÇ≤](bg:#000000 fg:#3A91DC)$symbol$context[ÓÇ∞](bg:#000000 fg:#3A91DC)]($style)"

[dotnet]
# disabled = true
symbol = " Óùø "
style = "bg:#4A35CC fg:#EEEEEE"
heuristic = true
format = "[[ÓÇ≤](bg:#000000 fg:#4A35CC)$symbol$version( ÔßΩ$tfm)[ÓÇ∞](bg:#000000 fg:#4A35CC)]($style)"

[elixir]
# disabled = true
symbol = " Óò≠ "
style = "bg:#4E2A8E fg:#EEEEEE"
format = '[[ÓÇ≤](bg:#000000 fg:#4E2A8E)$symbol$version \(OTP:$otp_version\)[ÓÇ∞](bg:#000000 fg:#4E2A8E)]($style)'

[elm]
# disabled = true
symbol = " Óò¨ " # original
style = "bg:#3E92D2 fg:#EEEEEE"
format = "[[ÓÇ≤](bg:#000000 fg:#3E92D2)$symbol$version[ÓÇ∞](bg:#000000 fg:#3E92D2)]($style)"

[env_var]
disabled = true
symbol = " Óûï "
style = "bg:#6f6a70 fg:#EEEEEE"
variable = "0"
default = "fish"
format = "([[ÓÇ≤](bg:#000000 fg:#6f6a70)$symbol$env_value[ÓÇ∞](bg:#000000 fg:#6f6a70)]($style))"

[erlang]
# disabled = true
symbol = " Óû± "
style = "bg:#8C032F fg:#EEEEEE"
format = "[[ÓÇ≤](bg:#000000 fg:#8C032F)$symbol$version[ÓÇ∞](bg:#000000 fg:#8C032F)]($style)"

[gcloud]
# disabled = true
symbol = " ‚òÅÔ∏è "
style = "bg:#1A73E8 fg:#EEEEEE"
format = '[[ÓÇ≤](bg:#000000 fg:#1A73E8)$symbol$account(\($region\))[ÓÇ∞](bg:#000000 fg:#1A73E8)]($style)'

[git_branch]
# disabled = true
symbol = " Ôû° "
style = "bg:#96ab5f fg:#111111"
# truncation_length = 4
# truncation_symbol = " "
format = "[[ÓÇ≤](bg:#000000 fg:#96ab5f)$symbol$branch[ÓÇ∞](bg:#000000 fg:#96ab5f)]($style)"

[git_commit]
# disabled = true
style = "bg:#E58F73 fg:#111111"
commit_hash_length = 4
# only_detached = true
format = "[[ÓÇ≤](bg:#000000 fg:#E58F73)#$hash[ÓÇ∞](bg:#000000 fg:#E58F73)]($style)"

[git_state]
# disabled = true
style = "bg:#E0B25D fg:111111"
rebase = "rebasing"
merge = "merging"
revert = "reverting"
cherry_pick = "Óäõ picking"
bisect = "bisecting"
am = "am'ing"
am_or_rebase = "am/rebase"
format = '\([[ÓÇ≤](bg:#000000 fg:#E0B25D)$state($progress_current/$progress_total)[ÓÇ∞](bg:#000000 fg:#E0B25D)]($style)\)'

[git_status]
# disabled = true
style = "bg:#E0B25D fg:#000000"
stashed = "ÔÄú ${count}"
ahead = "Ô≤ó ${count}"
behind = "Ô≤î ${count}"
diverged = "Ôß° ${ahead_count} ${behind_count}"
conflicted = "ÔÄ§${count}"
deleted = " ÔÄç${count}"
renamed = "Ô´¶${count}"
modified = " Ô•î${count}"
staged = " ÔÄå ${count}"
untracked = " Ôêé ${count}"
format = "([[ÓÇ≤](bg:#000000 fg:#E0B25D)$stashed$staged$modified$renamed$untracked$deleted$conflicted$ahead_behind[ÓÇ∞](bg:#000000 fg:#E0B25D)]($style))"

[golang]
# disabled = true
symbol = " Óòß "
style = "bg:#7FD5EA fg:#111111"
format = "[[ÓÇ≤](bg:#000000 fg:#7FD5EA)$symbol$version[ÓÇ∞](bg:#000000 fg:#7FD5EA)]($style)"

[helm]
# disabled = true
symbol = " Ô¥± "
style = "bg:#0F1689 fg:#EEEEEE"
format = "[[ÓÇ≤](bg:#000000 fg:#0F1689)$symbol$version[ÓÇ∞](bg:#000000 fg:#0F1689)]($style)"

[hostname]
disabled = false
style = "bg:#3388FF fg:#EEEEEE"
ssh_only = false
# trim_at = "."
format = "[@$hostname[ÓÇ∞](bg:#000000 fg:#3388FF)]($style)"

[java]
# disabled = true
symbol = " Óâñ "
style = "bg:#ED8B00 fg:#111111"
format = "[[ÓÇ≤](bg:#000000 fg:#ED8B00)$symbol$version[ÓÇ∞](bg:#000000 fg:#ED8B00)]($style)"

[jobs]
# disabled = true
symbol = "  ÔÄ∫ "
style = "bold bg:#000000 fg:#FFA200"
# threshold = 1
format = "[$symbol$number]($style)"

[julia]
# disabled = true
symbol = " Óò§ "
style = "bg:#4063D8 fg:#EEEEEE"
format = "[[ÓÇ≤](bg:#000000 fg:#4063D8)$symbol$version[ÓÇ∞](bg:#000000 fg:#4063D8)]($style)"

[kubernetes]
disabled = false
symbol = " ‚ò∏Ô∏é"
style = "bg:#3371E3 fg:#EEEEEE"
format = '[[ÓÇ≤](bg:#000000 fg:#3371E3)$symbol$context(\($namespace\))[ÓÇ∞](bg:#000000 fg:#3371E3)]($style)'

[memory_usage]
# disabled = false
symbol = " Ô°ö "
style = "bg:#BBBBBB fg:#111111"
threshold = 75
format = "([[ÓÇ≤](bg:#000000 fg:#BBBBBB)$symbol$ram(:$swap)[ÓÇ∞](bg:#000000 fg:#BBBBBB)]($style))"

# Mercurial
[hg_branch]
disabled = false
symbol = " ÓÇ† "
style = "bg:#96ab5f fg:#111111"
# truncation_length = 8 # default = 2^63 - 1
# truncation_symbol = " ‚Ä¶"
format = "[[ÓÇ≤](bg:#000000 fg:#96ab5f)$symbol$branch[ÓÇ∞](bg:#000000 fg:#96ab5f)]($style)"

[nim]
# disabled = true
symbol = " ÓâÆ "
style = "bg:#FFE953 fg:#111111"
format = "[[ÓÇ≤](bg:#000000 fg:#FFE953)$symbol$version[ÓÇ∞](bg:#000000 fg:#FFE953)]($style)"

[nix_shell]
# disabled = true
symbol = " Ôåì "
style = "bg:#27385D fg:#EEEEEE"
impure_msg = '[\(impure\)](bg:#27385D fg:#FF5511)'
pure_msg = '[\(pure\)](bg:#27385D fg:#AFD700)'
format = '[[ÓÇ≤](bg:#000000 fg:#27385D)$symbol$name$state[ÓÇ∞](bg:#000000 fg:#27385D)]($style)'

[nodejs]
# disabled = true
symbol = " Ô¢ò "
style = "bg:#005F00 fg:#EEEEEE"
format = "[[ÓÇ≤](bg:#000000 fg:#005F00)$symbol$version[ÓÇ∞](bg:#000000 fg:#005F00)]($style)"

[ocaml]
# disabled = true
symbol = " üê´ "
style = "bg:#F48B32 fg:#111111"
format = "[[ÓÇ≤](bg:#000000 fg:#F48B32)$symbol$version[ÓÇ∞](bg:#000000 fg:#F48B32)]($style)"

[package]
# disabled = true
symbol = " Ôíá "
style = "bg:#6F6A70 fg:#EEEEEE"
display_private = false
format = "[[ÓÇ≤](bg:#000000 fg:#6F6A70)$symbol$version[ÓÇ∞](bg:#000000 fg:#6F6A70)]($style)"

[perl]
# disabled = true
symbol = " üê™ "
style = "bg:#0073A1 fg:#EEEEEE"
format = "[[ÓÇ≤](bg:#000000 fg:#0073A1)$symbol$version[ÓÇ∞](bg:#000000 fg:#0073A1)]($style)"

[php]
# disabled = true
symbol = " Óòà "
style = "bg:#8892BF fg:#EEEEEE"
format = "[[ÓÇ≤](bg:#000000 fg:#8892BF)$symbol$version[ÓÇ∞](bg:#000000 fg:#8892BF)]($style)"

[purescript]
# disabled = true
symbol = " <=>"
style = "bg:#1D222D fg:#EEEEEE"
format = "[[ÓÇ≤](bg:#000000 fg:#1D222D)$symbol$version[ÓÇ∞](bg:#000000 fg:#1D222D)]($style)"

[python]
# disabled = true
symbol = " ÓòÜ "
style = "bg:#EBD45B fg:#111111"
# pyenv_version_name = true
pyenv_prefix = "pyenv "
python_binary = "python3"
format = '[[ÓÇ≤](bg:#000000 fg:#EBD45B)$symbol$pyenv_prefix$version(\($virtualenv\))[ÓÇ∞](bg:#000000 fg:#EBD45B)]($style)'

[ruby]
# disabled = true
symbol = " Ôêª "
style = "bg:#CC342D fg:#EEEEEE"
format = "[[ÓÇ≤](bg:#000000 fg:#CC342D)$symbol$version[ÓÇ∞](bg:#000000 fg:#CC342D)]($style)"

[rust]
# disabled = true
symbol = " Óû® "
style = "bg:#A72145 fg:#EEEEEE"
format = "[[ÓÇ≤](bg:#000000 fg:#A72145)$symbol$version[ÓÇ∞](bg:#000000 fg:#A72145)]($style)"

[shlvl]
# disabled = false
symbol = " ÔÖà"
style = "bold bg:#000000 fg:#FBDE2D"
threshold = 2
format = "[$symbol$shlvl]($style)"

[singularity]
# disabled = true
symbol = " ÓÇ∑SÓÇµ"
style = "bg:#1D315F fg:#EEEEEE"
format = '[[ÓÇ≤](bg:#000000 fg:#1D315F)$symbol\[$env\][ÓÇ∞](bg:#000000 fg:#1D315F)]($style)'

[swift]
# disabled = true
symbol = " ÔØ£ "
style = "bg:#F05138 fg:#EEEEEE"
format = "[[ÓÇ≤](bg:#000000 fg:#F05138)$symbol$version[ÓÇ∞](bg:#000000 fg:#F05138)]($style)"

[status]
# disabled = false
symbol = " ÔÑ™"
style = "bg:#000000 fg:#ff3322"
format = "[$symbol$status]($style)"

[terraform]
disabled = false
symbol = " Ô®à"
style = "bg:#5836CD fg:#EEEEEE"
format = '[[ÓÇ≤](bg:#000000 fg:#5836CD)$symbol\($workspace\)[ÓÇ∞](bg:#000000 fg:#5836CD)]($style)'
### uncomment the following, to see the version
# format = "[[ÓÇ∞](bg:#5836CD fg:#000000)$symbol$version($workspace)[ÓÇ∞](bg:#000000 fg:#5836CD)]($style)"

[username]
# disabled = true
show_always = true
style_root = "bold bg:#3388FF fg:#FF5511"
style_user = "bg:#3388FF fg:#EEEEEE"
format = "[[ÓÇ≤](bg:#000000 fg:#3388FF)$user]($style)"

[zig]
# disabled = true
symbol = " ÔºªZÔºΩ"
style = "bg:#F7A41D fg:#EEEEEE"
format = "[[ÓÇ≤](bg:#000000 fg:#F7A41D)$symbol$version[ÓÇ∞](bg:#000000 fg:#F7A41D)]($style)"
#EOF.
